/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment2;

import assignment2.model.MainModel;
import assignment2.view.MainView;
import com.sun.tools.javac.Main;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application{

    private static MainModel mainModel;
    private static MainView mainView;

    @Override
    public void start(Stage stage){
        stage.setTitle("Lite Snacks Vending Machine");
        mainView.setUp(stage);

    }

    public static void main(String[] args){

        mainModel = new MainModel("src/main/resources/Inventory.json",
                                    "src/main/resources/users.json",
                                "src/main/resources/InitialCash.json",
                                    "src/main/resources/credit_cards.json");
        mainView = new MainView(mainModel);
        
        launch();

    }
}
